### ISSUE TITLE
Attempting to delete a task from search results will result in deleting the wrong task

### ISSUE THREAD

**Issue by jin** [cs2103aug2014-w13-1c/main#135]
![screen shot 2014-10-19 at 4 54 45 pm](https://cloud.githubusercontent.com/assets/347918/4692587/ade5256a-576d-11e4-8e60-a3ff2dbe49dd.png)
![screen shot 2014-10-19 at 4 54 58 pm](https://cloud.githubusercontent.com/assets/347918/4692588/adebfdd6-576d-11e4-8913-72bdfa6b119e.png)
![screen shot 2014-10-19 at 4 55 04 pm](https://cloud.githubusercontent.com/assets/347918/4692585/ad8bbfa2-576d-11e4-9715-1b8e8fb6f2ec.png)
![screen shot 2014-10-19 at 4 55 10 pm](https://cloud.githubusercontent.com/assets/347918/4692586/ade3c472-576d-11e4-8dd0-09b8025c1523.png)

**Comment by acruis** [comment]
Also a problem for _update_ operations.

**Comment by lejolly** [comment]
much detailed, will look into it, thanks.

**Comment by lejolly** [comment]
810bb98d014ae577869f1d3693097a02a69c6922
