### ISSUE TITLE
Specify json file location

### ISSUE THREAD

**Issue by jin** [cs2103aug2014-w13-1c/main#14]

**Comment by acruis** [comment]
model already supports; assigning to controller

**Comment by jin** [comment]
@RyanAlexanderH both of the view and model are done, left with your link up

**Comment by acruis** [comment]
method to set/save file directory

#65

**Comment by RyanAlexanderH** [comment]
what's the command word for this?

**Comment by lejolly** [comment]
I think all you need to do is to expose the method from model manager then let the settings manager call that.

**Comment by acruis** [comment]
If you do want to use a command word, _saveto_.

**Comment by RyanAlexanderH** [comment]
85dfd1150b03452e802e4a1c9934cb33c14a8944

**Comment by jin** [comment]
https://github.com/cs2103aug2014-w13-1c/main/commit/85dfd1150b03452e802e4a1c9934cb33c14a8944

Can I have a commandcontroller method for this that doesn't require a command word?

**Comment by jin** [comment]
In RootViewController:

``` java
    public void closeSettings(File filePath) {
        if (filePath != null) {
            System.out.println(filePath.toString());
        }
        settingsView.toBack();
        settingsViewManager.cancelFocusOnButton();
        inputField.requestFocus();
    }
```

I just need a method to pass the filePath to.

**Comment by RyanAlexanderH** [comment]
2853cb820c4c87e9ebaae8656c6a73dbac2e68b6
