### ISSUE TITLE
Figure out a way to differentiate and deal with conflicts between keywords and words in the task name.

### ISSUE THREAD

**Issue by jin** [cs2103aug2014-w13-1c/main#156]

**Comment by jin** [comment]
Possible solution: Ignore keyword errors and treat them as part of the task name.

Example: "add watch the end of season 4 end today". The "of season 4" part will be inferred as a date, which will raise a date parsing error. Solution is to ignore this error and concat it to the original task name instead.

**Comment by acruis** [comment]
Agreed.

@RyanAlexanderH

**Comment by acruis** [comment]
#173

**Comment by RyanAlexanderH** [comment]
f40317f896b6a33dca70661251de4e46f42e98f9
