### ISSUE TITLE
Enhance visibility of current selected cell

### ISSUE THREAD

**Issue by jin** [cs2103aug2014-w13-1c/main#185]

**Comment by lejolly** [comment]
is this to make the currently selected listview cell more obvious?

**Comment by jin** [comment]
no, this was in response to prof's comments for the previous design. i think the current one looks OK

**Comment by lejolly** [comment]
i think we should make the currently selected cell a bit more obvious, should i create a new issue for this?

**Comment by jin** [comment]
no need, renamed this issue.
