### ISSUE TITLE
Usage guide when app is opened for the first time/empty task list

### ISSUE THREAD

**Issue by jin** [cs2103aug2014-w13-1c/main#21]

**Comment by jin** [comment]
Show if user launches app with empty task file

**Comment by lejolly** [comment]
can also just add a quick start paragraph or two below the "you have no tasks" line
something like this:

you seem to have no upcoming tasks!
- to add a task, just type "add <task name" to get started!
- to delete a task, etc...

**Comment by jin** [comment]
@lejolly ok i'll do this

**Comment by acruis** [comment]
@infinitus I'll assign @lejolly to write up the user guide

**Comment by lejolly** [comment]
12ed48dc49c3d2be6718cf40c4ee0ebfc0c802bb
