### ISSUE TITLE
More detailed error messages for user input

### ISSUE THREAD

**Issue by jin** [cs2103aug2014-w13-1c/main#22]

**Comment by jin** [comment]
Fixed in 6b8b50e

**Comment by lejolly** [comment]
do we want to give more descriptive error messages? cause everything now is just the same.

**Comment by acruis** [comment]
Yes.

**Comment by lejolly** [comment]
will work with @RyanAlexanderH to display more verbose error messages.

**Comment by acruis** [comment]
#210
