### ISSUE TITLE
Pass appropriate titles to title bar

### ISSUE THREAD

**Issue by acruis** [cs2103aug2014-w13-1c/main#227]

**Comment by acruis** [comment]
For #199

**Comment by acruis** [comment]
#230

**Comment by lejolly** [comment]
@infinitus what am i supposed to put in the title if the combo box shows the current sort style?

**Comment by jin** [comment]
Displaying completed/uncompleted/all or searching for "..."?

**Comment by lejolly** [comment]
ah ok

**Comment by lejolly** [comment]
88c4fbdc965be577705bf8cf13d69691fb411916
