### ISSUE TITLE
Better date parsing (e.g. 12/12/12 or today, tomorrow, yesterday, etc)

### ISSUE THREAD

**Issue by lejolly** [cs2103aug2014-w13-1c/main#46]

**Comment by lejolly** [comment]
some flexibility in format is required

**Comment by jin** [comment]
some ideas:

today, tomorrow, this <monday - sunday>, next <monday - sunday>, someday

mon == monday, tues == tuesday
can use substring matching for this. 
tu == tuesday, th == thursday

same thing goes for months

**Comment by RyanAlexanderH** [comment]
28df697341dba5dc8f13474a8196a0a6be59404e
