### ISSUE TITLE
Hotkey activation (for windows)

### ISSUE THREAD

**Issue by lejolly** [cs2103aug2014-w13-1c/main#47]
hotkey to bring app to front, and give focus to text input box.

**Comment by lejolly** [comment]
is this important enough to implement? please state why.

**Comment by jin** [comment]
**great** to have feature, but if you need to jump through too many hoops to get it to work, I think we should look elsewhere for niche features

**Comment by lejolly** [comment]
https://code.google.com/p/jintellitype/
