### ISSUE TITLE
Improve on the display of search results

### ISSUE THREAD

**Issue by lejolly** [cs2103aug2014-w13-1c/main#48]
two options
1. replace the current task list with a list of results
2. popup dialog box will include search results with detailed information
-- most importantly task item number
-- or have buttons to update/delete each search result (just like we currently have for the main task list, buttons will basically just pre-populate the text input area)

**Comment by jin** [comment]
can we do this like google's instant search? search as you type kinda thing

**Comment by lejolly** [comment]
AH, great idea too. so current task list will just update in real time then?

**Comment by jin** [comment]
yep. should be as simple as adding a search call in the inputField.textProperty().addListener

**Comment by lejolly** [comment]
d6618242cde5481c037a4b35a03faf53122f7e69
