### ISSUE TITLE
Proper support for 3 kinds of tasks

### ISSUE THREAD

**Issue by lejolly** [cs2103aug2014-w13-1c/main#49]
Support for timed tasks (i.e., has a start time and end time), tasks with deadline tasks (tasks that have to be done before a specific deadline), and floating tasks (tasks without specific times). Note that category names are temporary names only. You should figure out what are the best names for these categories. Are these names intuitive to end-users? Should they even care about consciously categorizing tasks?
- taken from the module handbook

few things to consider
- some form of visual differentiation between types of tasks (or are we just sticking to what dates are being shown?)
- support for changing of a particular task's type (in the update function)

**Comment by lejolly** [comment]
only the controller is lacking full support for this right? both gui and model have support.

**Comment by RyanAlexanderH** [comment]
db558e93ea864a8f32a64f514863a5b48e3527d0
