### ISSUE TITLE
Support for undos

### ISSUE THREAD

**Issue by lejolly** [cs2103aug2014-w13-1c/main#50]
- basic requirement is support of undo for last action
- do we want to do more than that?

**Comment by jin** [comment]
http://stackoverflow.com/questions/3541383/undo-redo-implementation

JavaFX undo framework:
https://github.com/TomasMikula/UndoFX

**Comment by lejolly** [comment]
ah nice, i'm using the RichTextFX framework from the same guy haha.

**Comment by acruis** [comment]
Wow nice

**Comment by acruis** [comment]
Support for parsing "undo" keyword in #168.

Undo logic being dealt with by @lejolly in #171.
